# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'swiftcsv' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for swiftcsv
  pod "SwiftCSV"

  target 'swiftcsvTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'swiftcsvUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
